name: CI

on:
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.4'

      - name: Copiar arquivo .env.example para .env
        run: cp .env.example .env

      - name: Instalar dependências do Composer
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Gerar chave da aplicação
        run: php artisan key:generate

      - name: Ajustar permissões
        run: chmod -R 777 storage bootstrap/cache

      - name: Criar banco de dados SQLite
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Instalar dependências do NPM
        run: npm install

      - name: Compilar assets
        run: npm run build

      - name: Executar testes (PHPUnit ou Pest)
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test --parallel

# - name: Execute Larastan
#   run: vendor/bin/phpstan analyse

# - name: Execute Laravel Pint
#   run: vendor/bin/pint --test
